[tool.poetry]
name = "try-nicegui"
version = "0.1.0"
description = ""
authors = ["Yusei Ito <me@yuseiito.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nicegui = "^1.3.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
